# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update contents

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
  - cron: "0 2 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn install
    - run: node ./scripts/stars.js
    - run: node ./scripts/packages.js
    - run: node ./scripts/languages.js
    - name: Commit & Push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A .
        git commit -m "contents refreshed"
        git push
